# Generated by Django 5.0 on 2024-09-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=300, verbose_name='Название услуги')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость услуги')),
                ('validity_period', models.PositiveIntegerField(verbose_name='Срок действия услуги (в днях)')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
