# Generated by Django 5.0 on 2024-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paid_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='key_word',
            field=models.CharField(max_length=50, null=True, verbose_name='Ключевое слово'),
        ),
    ]
