# Generated by Django 5.0 on 2024-08-14 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userfavorites_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorites',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
