# Generated by Django 5.0 on 2024-08-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0026_alter_advertisement_additional_information_view2'),
        ('users', '0007_alter_userfavorites_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='type',
        ),
        migrations.AddField(
            model_name='chat',
            name='advertisement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.advertisement'),
            preserve_default=False,
        ),
    ]
