# Generated by Django 5.0 on 2024-08-18 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_chat_subject_remove_chat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
