# Generated by Django 5.0 on 2024-08-18 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_chat_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
