# Generated by Django 5.0 on 2024-08-25 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0026_alter_advertisement_additional_information_view2'),
        ('users', '0010_alter_chat_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.advertisement'),
        ),
    ]
