# Generated by Django 5.0 on 2024-08-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0026_alter_advertisement_additional_information_view2'),
        ('users', '0011_alter_chat_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.store'),
        ),
    ]
