# Generated by Django 5.1.1 on 2024-10-09 23:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import services.files.uploaded_file
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('related_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название магазина')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на видеоролик YouTube')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to=services.files.uploaded_file.upload_to, verbose_name='Логотип')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_deactivate', models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный магазин')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт магазина')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('counter_views', models.IntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related_data.category', verbose_name='Категория')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related_data.region', verbose_name='Регион')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший магазин')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='store_store_search__d19774_gin')],
            },
        ),
    ]
