# Generated by Django 5.1.1 on 2024-10-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='moderated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Прошло модерацию'),
        ),
    ]
