# Generated by Django 5.1.1 on 2024-10-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='moderation_error_message',
            field=models.TextField(blank=True, help_text='Отправиться пользователю на Email', null=True, verbose_name='Текст причины отказа в модерации'),
        ),
    ]
