# Generated by Django 5.0 on 2024-08-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0005_publication_search_title_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organization', models.CharField(max_length=255, verbose_name='Название организации')),
                ('unp', models.CharField(max_length=9, verbose_name='УНП')),
                ('legal_address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('phone_num', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Об организации',
                'verbose_name_plural': 'Об организации',
            },
        ),
    ]
