# Generated by Django 5.0 on 2024-09-19 14:11

import advertisement.utils_for_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0007_remove_publication_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='preview_image',
            field=models.ImageField(upload_to=advertisement.utils_for_models.upload_to, verbose_name='Фото'),
        ),
    ]
