# Generated by Django 5.1.1 on 2024-10-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavorites',
            options={'verbose_name': 'Избранное пользователя', 'verbose_name_plural': 'Избранное пользователя'},
        ),
    ]
