# Generated by Django 5.1.1 on 2024-10-28 15:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_userfavorites_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorites',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None, verbose_name='Список избранного'),
        ),
    ]
