# Generated by Django 5.1.1 on 2024-10-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_userfavorites_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorites',
            name='notes_for_favorites',
            field=models.JSONField(blank=True, default=dict, verbose_name='Список заметок для избранного'),
        ),
    ]
