# Generated by Django 5.1.1 on 2024-10-09 23:45
from django.contrib.postgres.operations import TrigramExtension

import advertisement.models
import dirtyfields.dirtyfields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.text
import services.files.uploaded_file
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('related_data', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='ReasonOfComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000, verbose_name='Причина жалобы')),
            ],
            options={
                'verbose_name': 'Причина жалобы',
                'verbose_name_plural': 'Причины жалобы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул')),
                ('title', models.CharField(db_index=True, max_length=255, validators=[utils.validators.validate_words], verbose_name='Заголовок')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Цена')),
                ('bearer', models.CharField(choices=[('Частное лицо', 'Частное лицо'), ('Компания', 'Компания')], default='Частное лицо', max_length=50, verbose_name='Податель')),
                ('preview_image', models.ImageField(blank=True, default=None, null=True, upload_to=services.files.uploaded_file.upload_to, verbose_name='Главная фотография')),
                ('additional_information', models.JSONField()),
                ('contact_name', models.CharField(max_length=255, validators=[utils.validators.validate_words], verbose_name='Контактное лицо')),
                ('phone_num', models.CharField(max_length=255, validators=[utils.validators.validate_phone], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('description', models.TextField(validators=[utils.validators.validate_words], verbose_name='Описание')),
                ('video_link', models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на видео')),
                ('counter_views', models.IntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True, verbose_name='URL')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объявления')),
                ('date_of_delete', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления объявления')),
                ('date_of_deactivate', models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации объявления')),
                ('vip', models.BooleanField(default=False, verbose_name='Сделать VIP-объявлением')),
                ('shown_vip', models.BooleanField(default=False, verbose_name='Показано на главной странице')),
                ('shown_vip_count', models.IntegerField(default=0, verbose_name='Счетчик показов на главной странице')),
                ('shown_vip_category', models.BooleanField(default=False, verbose_name='Показано на странице категории')),
                ('shown_vip_category_count', models.IntegerField(default=0, verbose_name='Счетчик показов на странице категории')),
                ('date_of_deactivate_vip', models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации VIP')),
                ('highlight_ad', models.BooleanField(default=False, verbose_name='Выделить объявление')),
                ('date_of_deactivate_highlight_ad', models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации выделения')),
                ('special_accommodation', models.BooleanField(default=False, verbose_name='Спецразмещение')),
                ('date_of_deactivate_special_accommodation', models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации спецразмещения')),
                ('raise_in_search', models.BooleanField(default=False, verbose_name='Поднять в поиске')),
                ('search_boost_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата поднятия в поиске')),
                ('moderated', models.BooleanField(blank=True, null=True, verbose_name='Прошло модерацию')),
                ('is_active', models.BooleanField(default=False, verbose_name='Объявление активно')),
                ('additional_information_view', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None), blank=True, editable=False, null=True, size=None)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('search_title_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related_data.category', verbose_name='Раздел')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related_data.region', verbose_name='Регион, город, район')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PhotoAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=services.files.uploaded_file.upload_to, verbose_name='Фото')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.advertisement', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фото объявления',
                'verbose_name_plural': 'Фото объявлений',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Обоснование жалобы')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания жалобы')),
                ('user', models.CharField(max_length=500, verbose_name='Пользователь, отправивший жалобу')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.advertisement', verbose_name='Объявление, на которое пожаловались')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.reasonofcomplaint', verbose_name='Причина жалобы')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_upload_file', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки файла')),
                ('file', models.FileField(upload_to=advertisement.models.UploadFile.get, verbose_name='Путь к файлу с объявлениями')),
                ('status', models.BooleanField(default=False, verbose_name='Статус обработки файла')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
        migrations.CreateModel(
            name='ErrorFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_upload_file', models.DateTimeField(auto_now_add=True, verbose_name='Время создания файла')),
                ('file', models.CharField(max_length=255, verbose_name='Путь к файлу с объявлениями с ошибками')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('upload_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.uploadfile', verbose_name='Загруженный файл')),
            ],
            options={
                'verbose_name': 'Файл с объявлениями с ошибками',
                'verbose_name_plural': 'Файлы с объявлениями с ошибками',
            },
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='advertiseme_search__421054_gin'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_title_vector'], name='advertiseme_search__07fa62_gin'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_gin_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='title_upper_gin_index'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date_of_create'], name='advertiseme_date_of_2c3be1_brin'),
        ),
    ]
