# Generated by Django 5.1.1 on 2024-10-12 15:43

import django.db.models.deletion
import services.files.uploaded_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Жалоба на объявление', 'verbose_name_plural': 'Жалобы на объявления'},
        ),
        migrations.AlterModelOptions(
            name='errorfile',
            options={'verbose_name': 'Файл с ошибками объявлений при массовом импорте', 'verbose_name_plural': 'Файлы с ошибками объявлений при массовом импорте'},
        ),
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'verbose_name': 'Загруженный файл с объявлениями для массового импорта', 'verbose_name_plural': 'Загруженные файлы с объявлениями для массового импорта'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='date_of_last_activation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней активации'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='additional_information',
            field=models.JSONField(verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='photoadvertisement',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.advertisement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='photoadvertisement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=services.files.uploaded_file.upload_to, verbose_name='Фотография'),
        ),
    ]
