# Generated by Django 5.1.1 on 2024-10-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_complaint_options_alter_errorfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Oбъявление', 'verbose_name_plural': 'Oбъявления'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='moderation_error_message',
            field=models.TextField(blank=True, help_text='Отправиться пользователю на Email', null=True, verbose_name='Текст причины отказа в модерации'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date_of_last_activation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней активации объявления'),
        ),
    ]
