# Generated by Django 5.0 on 2024-08-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0021_store_search_vector_and_more'),
        ('advertisement', '0022_merge_20240811_1730'),
    ]

    operations = [
    ]
