# Generated by Django 5.0 on 2024-08-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0023_merge_20240812_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='bearer',
            field=models.CharField(choices=[('Частное лицо', 'Частное лицо'), ('Компания', 'Компания')], default='Частное лицо', max_length=50, verbose_name='Податель'),
        ),
    ]
