# Generated by Django 5.0 on 2024-08-15 10:55

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0024_alter_advertisement_bearer'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='advertisement',
            name='additional_information_view2',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
