# Generated by Django 5.0 on 2024-08-15 11:01

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0025_advertisement_additional_information_view2'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AlterField(
            model_name='advertisement',
            name='additional_information_view2',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
