# Generated by Django 5.0 on 2024-08-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0026_alter_advertisement_additional_information_view2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='date_of_change',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='date_of_delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления объявления'),
        ),
    ]
