# Generated by Django 5.0 on 2024-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0027_remove_advertisement_date_of_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/store_img', verbose_name='Логотип'),
        ),
    ]
