# Generated by Django 5.0 on 2024-08-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0028_alter_store_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='additional_information_view2',
        ),
    ]
