# Generated by Django 5.0 on 2024-09-20 14:36

import advertisement.utils_for_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0029_remove_advertisement_additional_information_view2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='moderated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Прошло модерацию'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=advertisement.utils_for_models.upload_to, verbose_name='Логотип'),
        ),
    ]
