# Generated by Django 5.0 on 2024-09-10 13:31

import advertisement.utils_for_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0029_remove_advertisement_additional_information_view2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorfile',
            name='status',
        ),
        migrations.AddField(
            model_name='errorfile',
            name='upload_file',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='advertisement.uploadfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=advertisement.utils_for_models.upload_to, verbose_name='Логотип'),
        ),
    ]
