# Generated by Django 5.0 on 2024-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0030_alter_advertisement_moderated_alter_store_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='moderated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Прошло модерацию'),
        ),
    ]
