# Generated by Django 5.0 on 2024-09-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0030_remove_errorfile_status_errorfile_upload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorfile',
            name='upload_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisement.uploadfile'),
        ),
    ]
