# Generated by Django 5.0 on 2024-09-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0031_alter_errorfile_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус обработки файла'),
        ),
    ]
