# Generated by Django 5.0 on 2024-09-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0031_alter_advertisement_moderated'),
        ('advertisement', '0032_uploadfile_status'),
    ]

    operations = [
    ]
