# Generated by Django 5.0 on 2024-09-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0033_merge_20240920_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='date_of_deactivate_highlight_ad',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации выделения'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='date_of_deactivate_raise_in_search',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата поднятия в поиске'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='date_of_deactivate_special_accommodation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации спецразмещения'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='date_of_deactivate_vip',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации VIP'),
        ),
    ]
