# Generated by Django 5.0 on 2024-09-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0033_merge_20240920_1343'),
        ('advertisement', '0033_merge_20240920_1344'),
    ]

    operations = [
    ]
