# Generated by Django 5.0 on 2024-09-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0034_advertisement_date_of_deactivate_highlight_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='shown_vip',
            field=models.BooleanField(default=False, verbose_name='Показано на главной странице'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='shown_vip_cat',
            field=models.BooleanField(default=False, verbose_name='Показано на странице категории'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='shown_vip_count',
            field=models.IntegerField(default=0, verbose_name='Счетчик показов'),
        ),
    ]
