# Generated by Django 5.0 on 2024-09-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0034_merge_20240920_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='date_of_deactivate_highlight_ad',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации выделения'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='date_of_deactivate_raise_in_search',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата поднятия в поиске'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='date_of_deactivate_special_accommodation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации спецразмещения'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='date_of_deactivate_vip',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации VIP'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='shown_vip',
            field=models.BooleanField(default=False, verbose_name='Показано на главной странице'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='shown_vip_cat',
            field=models.BooleanField(default=False, verbose_name='Показано на странице категории'),
        ),
    ]
