# Generated by Django 5.0 on 2024-09-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0035_advertisement_shown_vip_advertisement_shown_vip_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='shown_vip_cat_count',
            field=models.IntegerField(default=0, verbose_name='Счетчик показов на странице категории'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='shown_vip_count',
            field=models.IntegerField(default=0, verbose_name='Счетчик показов на главной странице'),
        ),
    ]
