# Generated by Django 5.0 on 2024-09-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0035_advertisement_date_of_deactivate_highlight_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='shown_vip_count',
            field=models.IntegerField(default=0, verbose_name='Счетчик показов'),
        ),
    ]
