# Generated by Django 5.0 on 2024-09-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0036_advertisement_shown_vip_cat_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='shown_vip_cat',
            new_name='shown_vip_category',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='shown_vip_cat_count',
            new_name='shown_vip_category_count',
        ),
    ]
