# Generated by Django 5.0 on 2024-10-02 11:02

import advertisement.utils_for_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0037_rename_shown_vip_cat_advertisement_shown_vip_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='preview_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=advertisement.utils_for_models.upload_to, verbose_name='Главная фотография'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
