# Generated by Django 5.0 on 2024-10-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0038_alter_advertisement_preview_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='date_of_deactivate_raise_in_search',
            new_name='search_boost_date',
        ),
    ]
