# Generated by Django 5.1.1 on 2024-10-09 23:45

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organization', models.CharField(max_length=255, verbose_name='Название организации')),
                ('unp', models.CharField(max_length=9, verbose_name='УНП')),
                ('legal_address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('phone_num', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Об организации',
                'verbose_name_plural': 'Об организации',
            },
        ),
        migrations.CreateModel(
            name='BadWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Нецензурное слово',
                'verbose_name_plural': 'Нецензурные слова',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст помощи')),
            ],
            options={
                'verbose_name': 'Текст страницы помощь',
                'verbose_name_plural': 'Текст страницы помощь',
            },
        ),
    ]
