# Generated by Django 5.1.1 on 2024-10-28 12:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст страницы оплата',
                'verbose_name_plural': 'Текст страницы оплата',
            },
        ),
    ]
