# Generated by Django 5.0 on 2024-08-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_domer', '0006_aboutorganization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='video_link',
        ),
    ]
