# Generated by Django 5.1.1 on 2024-10-09 23:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django_ckeditor_5.fields
import services.files.uploaded_file
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('announcement', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Аннотация')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст статьи')),
                ('preview_image', models.ImageField(upload_to=services.files.uploaded_file.upload_to, verbose_name='Фото')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('counter_views', models.IntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('moderated', models.BooleanField(default=False, verbose_name='Прошло модерацию')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('search_title_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='publication_search__bbb6d7_gin'), django.contrib.postgres.indexes.GinIndex(fields=['search_title_vector'], name='publication_search__e53b7e_gin')],
            },
        ),
    ]
