# Generated by Django 5.1.1 on 2024-10-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_publication_moderation_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='moderated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Прошло модерацию'),
        ),
    ]
