# Generated by Django 5.1.1 on 2024-10-09 23:45

import django.contrib.postgres.fields
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок элемента')),
            ],
            options={
                'verbose_name': 'Элемент для списка',
                'verbose_name_plural': 'Элементы для списка',
            },
        ),
        migrations.CreateModel(
            name='Spisok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок списка')),
            ],
            options={
                'verbose_name': 'Список элементов для полей',
                'verbose_name_plural': 'Списки элементов для полей',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Категория')),
                ('type', models.CharField(choices=[('category_1', 'category_1'), ('category_2', 'category_2'), ('category_3', 'category_3'), ('category_4', 'category_4')], max_length=255, verbose_name='Уровень категории')),
                ('fav_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок на вкладке')),
                ('keywords', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Ключевые слова')),
                ('keywords_description', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Meta описание')),
                ('main_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Главный заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='related_data.category', verbose_name='Отношение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ElementTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загловок второго элемента')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related_data.element', verbose_name='Связь с элементом')),
            ],
            options={
                'verbose_name': 'Дополнительный элемент для списка',
                'verbose_name_plural': 'Дополнительные элементы для списка',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255, verbose_name='Область, город')),
                ('type', models.CharField(choices=[('Область', 'Область'), ('Город', 'Город')], max_length=255, verbose_name='Тип местонахождения')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='related_data.region', verbose_name='Отношение')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля')),
                ('title_ad', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок для администратора')),
                ('error', models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст ошибки при неверно введенных данных')),
                ('int_val_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Список числовых значений для задания диапазонов фильтрации'), blank=True, default=list, null=True, size=None)),
                ('min_val_interval_date', models.IntegerField(blank=True, null=True, verbose_name='Минимально возможный год для выбора')),
                ('max_val_interval_date', models.IntegerField(blank=True, null=True, verbose_name='Максимально возможный год для выбора')),
                ('search', models.CharField(blank=True, max_length=500, null=True, verbose_name='Поле для поиска')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='related_data.category', verbose_name='Связь с категорией')),
                ('spisok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='related_data.spisok', verbose_name='Связь со списком')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.AddField(
            model_name='element',
            name='spisok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related_data.spisok', verbose_name='Связь со списком'),
        ),
    ]
