# Generated by Django 5.1.1 on 2024-10-15 19:27

import django.contrib.postgres.fields
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kатегория', 'verbose_name_plural': 'Kатегории'},
        ),
        migrations.AlterModelOptions(
            name='elementtwo',
            options={'verbose_name': 'Дополнительное значение элемента для списка', 'verbose_name_plural': 'Дополнительные значения элементов для списка'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Поле дополнительной информации объявления по категории', 'verbose_name_plural': 'Поля дополнительной информации объявления по категории'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Pегион', 'verbose_name_plural': 'Pегионы'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='related_data.category', verbose_name='Отношение к категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('category_1', 'Уровень 1'), ('category_2', 'Уровень 2'), ('category_3', 'Уровень 3'), ('category_4', 'Уровень 4')], max_length=255, verbose_name='Уровень категории'),
        ),
        migrations.AlterField(
            model_name='field',
            name='int_val_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, default=list, help_text='Укажите значения через запятую, прим. 100,200,300', null=True, size=None, verbose_name='Список числовых значений для задания диапазонов фильтрации'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='related_data.region', verbose_name='Отношение к области'),
        ),
    ]
